version: '3.8'

services:
  # Solo la aplicaci贸n y base de datos para producci贸n
  app:
    build: .
    container_name: sensor-app-prod
    ports:
      - "6060:6060"
    environment:
      - DATABASE_URL=postgresql://sensor_user:sensor_pass@db:5432/sensor_db
      - DEBUG=false
      - SECRET_KEY=${SECRET_KEY:-production-secret-key-change-this}
    depends_on:
      - db
    networks:
      - sensor-network
    restart: unless-stopped
    # Sin volumen montado para producci贸n

  # Base de datos PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: sensor-db-prod
    environment:
      - POSTGRES_DB=sensor_db
      - POSTGRES_USER=sensor_user
      - POSTGRES_PASSWORD=sensor_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sensor-network
    restart: unless-stopped
    # No exponer puerto en producci贸n por seguridad

volumes:
  postgres_data:

networks:
  sensor-network:
    driver: bridge
